# Generated by Django 3.2.9 on 2022-05-28 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='health_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='medical_provider_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_provider', to='users.medicalprovider'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='medical_setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_setting', to='users.medicalsetting'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='medical_specialty',
            field=models.ManyToManyField(related_name='medical_specialty', to='disease.DiseaseCategories'),
        ),
        migrations.DeleteModel(
            name='ProfessionalProfile',
        ),
    ]
