# Generated by Django 3.2.9 on 2022-01-28 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0001_initial'),
        ('likereviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likereview',
            name='reviewID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_like_review', to='review.review'),
        ),
    ]
