# Generated by Django 3.2.9 on 2022-05-22 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treatment', '0001_initial'),
        ('disease', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_treatment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatment',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_disease', to='disease.disease'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_treatment_category', to='treatment.treatmentcategories'),
        ),
        migrations.AddConstraint(
            model_name='treatment',
            constraint=models.UniqueConstraint(fields=('disease', 'treatment_name', 'treatment_categories'), name='unique treatment name'),
        ),
    ]
