# Generated by Django 3.2.9 on 2022-03-19 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlike',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_like_review_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_comment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_comment_review', to='review.review'),
        ),
        migrations.AddField(
            model_name='review',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_review_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_review_treatment', to='treatment.treatment'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewlike',
            unique_together={('reviewID', 'sender')},
        ),
    ]
