# Generated by Django 3.2.9 on 2022-03-27 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='create_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fk_review_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
