# Generated by Django 3.2.9 on 2022-06-02 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0003_favoritedisease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritedisease',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_disease', to='disease.disease'),
        ),
        migrations.AddConstraint(
            model_name='favoritedisease',
            constraint=models.UniqueConstraint(fields=('user', 'disease'), name='favorite_once'),
        ),
    ]
