# Generated by Django 3.2.9 on 2022-06-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0004_auto_20220603_0240'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='disease',
            constraint=models.UniqueConstraint(fields=('disease_categories', 'disease_categories'), name='unique disease name'),
        ),
    ]
