# Generated by Django 3.2.9 on 2022-06-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0006_auto_20220613_1252'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='disease',
            name='unique disease name',
        ),
    ]
